use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Eq, PartialEq)]
pub enum SequenceType {
    String,
    StringVec,
    Int,
    IntVec,
    Float,
    FloatVec,
    Bool,
    BoolVec,
    Gene,
    GeneVec,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Eq, PartialEq)]
pub enum NormalizedArtifact {
    Promoter,
    ProblemAssertionManifest,
    Executable,
    Ribozyme,
    ProjectedIntent,
    Spacer,
    Protospacer,
    Phenotype,
    EnterpriseNegotiationHandoverCertificate,
    Silencer,
    StrategicNote,
    SemanticNarrowing,
    SemanticConstraintAssumption,
    Microalignment,
    StopImplementation,
    DeferredScope,
    Intron,
    ManagedRequirement,
    Exon,
    ResourceReference,
    TaskRealization,
    TaskRealizationFramework,
    TestRegressionCriteria,
    TestObjectiveManifest,
    TestOrchestrationManifest,
    CentralRuntimeManifest,
    CountermeasureAssessmentSystem,
    ProductionTestedImplementation,
    Chaperone,
    TaskMediation,
    CausalResolution,
    TraceReport,
    LongNarrativeContext,
    CircularInstitutionalReferenceContext,
    SuggestedChanges,
}
