use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Eq, PartialEq)]
pub enum DnapError {
    BlankInsulatorName,
    BlankPlacementRegion,
    BlankGenomeName,
    BlankGrnName,
    BlankTfDisplayName,
    BlankGeneFamilyName,
    BlankGeneFamilyAbbreviation,
    BlankSequenceDefinitionName,
    DuplicateSequenceDefinitionName,
    DuplicateGeneFamilyAbbreviation,
    DuplicateActiveAllele,
    MissingNormalizedArtifact,
    BlankLocusName,
    BlankGeneFamilyLookup,
    BlankMutationSequenceName,
    BlankExonText,
    GeneFamilyNotFound,
    SequenceDefinitionNotFound,
    AmbiguousSequenceDefinition,
    SequenceValueTypeMismatch,
    GeneFqnNotFound,
    AmbiguousGeneFqn,
    AlleleNotFound,
    AlleleCannotMutate,
    LgtmRequiresUnexpressedMutation,
    ExonsNotFound,
    SemanticNarrowingTargetRequired,
    BlankSemanticNarrowingTitle,
    BlankSemanticNarrowingAnswer,
    SemanticNarrowingNotFound,
    AmbiguousSemanticNarrowing,
    DuplicateSemanticNarrowingTitle,
    SemanticNarrowingCauseRequiresAnswer,
    InsulatorNotFound,
    GenomeNotFound,
    GenomeInsulatorMismatch,
    GrnNotFound,
    GrnGenomeMismatch,
    TfNotFound,
    TfInsulatorMismatch,
}
