use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Eq, PartialEq)]
pub enum DnapError {
    BlankInsulatorName,
    BlankPlacementRegion,
    BlankGenomeName,
    BlankTfDisplayName,
    BlankGeneFamilyName,
    BlankGeneFamilyAbbreviation,
    BlankSequenceDefinitionName,
    DuplicateSequenceDefinitionName,
    DuplicateGeneFamilyAbbreviation,
    DuplicateActiveAllele,
    MissingNormalizedArtifact,
    BlankLocusName,
    BlankGeneFamilyLookup,
    BlankMutationSequenceName,
    BlankExonText,
    GeneFamilyNotFound,
    SequenceDefinitionNotFound,
    AmbiguousSequenceDefinition,
    SequenceValueTypeMismatch,
    GeneFqnNotFound,
    AmbiguousGeneFqn,
    AlleleNotFound,
    AlleleCannotMutate,
    LgtmRequiresUnexpressedMutation,
    ExonsNotFound,
    EnhancerContextEnhancerRequired,
    EnhancerContextPromoterRequired,
    IntronTargetRequired,
    BlankIntronTitle,
    BlankIntronAnswer,
    IntronNotFound,
    AmbiguousIntron,
    DuplicateIntronTitle,
    IntronCauseRequiresAnswer,
    InsulatorNotFound,
    GenomeNotFound,
    GenomeInsulatorMismatch,
    TfNotFound,
    TfInsulatorMismatch,
}
